devices:
  - name: R1
    source: containerlab
    platform: frr
    role: router
    container: clab-complinet-r1
    baseline: R1.cfg
    enabled: true

  - name: R2
    source: containerlab
    platform: frr
    role: router
    container: clab-complinet-r2
    baseline: R2.cfg
    enabled: true
