devices:
  - name: R1
    source: containerlab
    container: clab-complinet-r1
    role: router
    baseline: R1.cfg

  - name: R2
    source: containerlab
    container: clab-complinet-r2
    role: router
    baseline: R2.cfg
