devices:
  - name: R1
    host: 192.168.100.11
    device_type: cisco_ios
    role: router
    baseline: cisco_router.cfg

  - name: SW1
    host: 192.168.100.21
    device_type: cisco_ios
    role: switch
    baseline: cisco_switch.cfg
